# Creating Arrays
---

In [2]:
import numpy as np

### Creating Arrays through Python Lists
---

In [3]:
np.array([1,2,3]) # Integer array

array([1, 2, 3])

If the data type of all entries in list is not similar, then numpy will upcast it.

In [4]:
np.array([3.14,5,6]) # upcasting from int to float

array([3.14, 5.  , 6.  ])

In [9]:
np.array(["dev",5,6,3,3.14]) # upcasting from int, float to string

array(['dev', '5', '6', '3', '3.14'], dtype='<U32')

we can also specify the data type of the entries of the array by using `dtype` attribute.

In [9]:
np.array([5,6,3,3.14], dtype = np.float32)

array([5.  , 6.  , 3.  , 3.14], dtype=float32)

We can also create multidimensional Arrays with lists

In [12]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating arrays through scratch
---
- It is not adviced to create arrays from lists.
- For larger arrays, it is efficient to create arrays from numpy builtins functions and attributes.

In [13]:
np.zeros((10), dtype=int) # an 1-D integer array filled with 10-zeros 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones((3,3),dtype = int) # an 2-D integer array filled with 9 ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# Create a 3x5 array filled with 3.14
np.full((3, 3), 3.1) # creating an 3 X 3 array with each entry as 3.1

array([[3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1]])

In [14]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
# Create a 3x3 array of uniformly distributed
# pseudorandom values between 0 and 1
np.round(np.random.random((3,3)),2)

array([[0.47, 0.93, 0.47],
       [0.85, 0.29, 0.96],
       [0.5 , 0.37, 0.45]])

In [30]:
# Create a 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 2.37302618, -0.11723214, -0.39596576],
       [ 0.76436177, -0.47955476, -0.81449508],
       [-0.86138905,  1.20958501,  0.22546713]])

In [34]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0, 10, (3,3))

array([[6, 0, 7],
       [9, 7, 0],
       [2, 4, 8]], dtype=int32)

In [35]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
# Create an uninitialized array of three integers; the values will be
# whatever happens to already exist at that memory location
np.empty((3))

array([1., 1., 1.])

### Numpy Attributes
---

In [19]:
rng = np.random.default_rng(seed=1701)  # seed for reproducibility

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array

In [21]:
print("x3 ndim: ", x3.ndim) # Dimension = levels in array
print("x3 shape:", x3.shape) # Shape= give number of elements in each level
print("x3 size: ", x3.size) # size = total number of elements in array
print("dtype:   ", x3.dtype) #dtype =  returns the data type of array

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


### Array Indexing
---

Accessing Single Element in 1-D

In [35]:
arr = np.random.randint(0,50,(10)) # creating an array of size 10 with entries ranging in [0,50)
print(arr[0]) # printing the first element in the array
print(arr[-1]) # printing the last element in the array


13
21


Accessing Single Element in 2-D

In [53]:
arr = np.random.randint(0,101,(3,3)) # creating an 2-D array of size 3 X 3 with entries ranging in [0,101)
print(arr[0]) # printing the first row in the array
print(arr[-1]) # printing the last row in the array
print(arr[0,0]) # printing the first element
print(arr[0,-1]) # printing the last element of first row

[38 17 49]
[64 45 53]
38
49


Values can also be modified using any of the preceding index notation:

In [57]:
arr[0,-1] = 50.5 # as the arr is of integer type the value will be truncated

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value into an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

### Array Slicing:
---

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

x[start: stop: step]

If any of these are unspecified, they default to the values start=0, stop= < size of dimension >, step=1. Let's look at some examples of accessing subarrays in one dimension and in multiple dimensions.

#### Single Dimensional subarrays

In [67]:
arr = np.random.randint(0,101,(10)) # Creating an array with 10 random integer values ranging from [0,101)
print(arr[0:5]) # First Five elements
print(arr[:-4:-1]) # last three elements
print(arr[::-1]) # whole reversed array


[28 43 56 16 24]
[ 9 71 97]
[ 9 71 97  1 51 24 16 56 43 28]


#### Multi-Dimensional subarrays

In [84]:
arr = np.random.randint(0,101,(3,3))

In [85]:
# you can do same in this also, but remember that here , separates the levels or dimensions 
print(arr[::-1,::-1])   # here first means before comma is for rows and second means after comma is for columns.

[[86 70 12]
 [ 4 73 47]
 [22 35 89]]


### Array Copying
---

#### Subarrays as No-Copy Views

Unlike Python list slices, NumPy array slices are returned as *views* rather than *copies* of the array data.
Consider our two-dimensional array from before:

In [87]:
arr

array([[89, 35, 22],
       [47, 73,  4],
       [12, 70, 86]], dtype=int32)

Let's extract a $2 \times 2$ subarray from this:

In [90]:
arr_sub = arr[:2,:2]
print(arr_sub)

[[89 35]
 [47 73]]


Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [92]:
arr_sub[0,0] = 999
print(arr)

[[999  35  22]
 [ 47  73   4]
 [ 12  70  86]]


Some users may find this surprising, but it can be advantageous: for example, when working with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

#### Creating copies of array
Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the `copy` method:

In [93]:
arr

array([[999,  35,  22],
       [ 47,  73,   4],
       [ 12,  70,  86]], dtype=int32)

In [94]:
arr_sub  = arr[:2,:2].copy()
arr_sub[0,0] = 0
print(arr)

[[999  35  22]
 [ 47  73   4]
 [ 12  70  86]]


### Reshaping of arrays
---
Another useful type of operation is reshaping of arrays, which can be done with the `reshape` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [99]:
arr = np.random.randint(0,10,(9)).reshape(3,3)

In [115]:
x =np.array([1,2,3])
x.reshape((3, 1))  # column vector via reshape

array([[1],
       [2],
       [3]])

In [118]:
x.reshape((1, 3))  # row vector via reshape

array([[1, 2, 3]])

A convenient shorthand for this is to use `np.newaxis` in the slicing syntax:

In [122]:
x[np.newaxis,:] # row vector using np.newaxis

array([[1, 2, 3]])

In [123]:
x[:,np.newaxis] # column vector using np.newaxis

array([[1],
       [2],
       [3]])

### Concatenation of Arrays
---
Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines `np.concatenate`, `np.vstack`, and `np.hstack`.

#### Concatenation
`np.concatenate` takes a tuple or list of arrays as its first argument, as you can see here:

**NOTE**: in `concatenate` all input must have same number of dimensions

In [127]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [128]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


And it can be used for two-dimensional arrays:

In [131]:
grid = np.array([[1, 2, 3],[4, 5, 6]])

np.concatenate([grid, grid]) # concatenate along the first axis ( or as rows)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [133]:
# concatenate along the second axis (zero-indexed) ( or as columns)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### vstack and hstack
For working with arrays of mixed dimensions, it can be clearer to use the `np.vstack` (vertical stack) and `np.hstack` (horizontal stack) functions:

**NOTE** in `vstack` both arrays must have same number of columns

**NOTE** in `hstack` both arrays must have same number of rows

In [135]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [138]:
# horizontally stack the arrays
y = np.array([[99],[99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

Similarly, for higher-dimensional arrays, np.dstack will stack arrays along the third axis.

### Splitting of arrays
---
The opposite of concatenation is splitting, which is implemented by the functions `np.split`, `np.hsplit`, and `np.vsplit`.  For each of these, we can pass a list of indices giving the split points:

In [142]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that *N* split points leads to *N* + 1 subarrays.
The related functions `np.hsplit` and `np.vsplit` are similar:

In [143]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [144]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [145]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, for higher-dimensional arrays, `np.dsplit` will split arrays along the third axis.

## Universal Functions
---
- Universal functions also known as Ufuncs are very fast.


### Array Arithmetic 
- Arithmetic operators will work for each element in the array

In [16]:
x = np.arange(5)
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x      = [0 1 2 3 4]
x + 5  = [5 6 7 8 9]
x - 5  = [-5 -4 -3 -2 -1]
x * 2  = [0 2 4 6 8]
x / 2  = [0.  0.5 1.  1.5 2. ]
x // 2 = [0 0 1 1 2]
-x     =  [ 0 -1 -2 -3 -4]
x ** 2 =  [ 0  1  4  9 16]
x % 2  =  [0 1 0 1 0]


In addition, these can be strung together however you wish, and the standard order of operations is respected:

In [17]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25, -9.  ])

All of these arithmetic operations are simply convenient wrappers around specific ufuncs built into NumPy. For example, the + operator is a wrapper for the add ufunc:

In [18]:
np.add(x, 2)

array([2, 3, 4, 5, 6])

The following table lists the arithmetic operators implemented in NumPy:

| Operator    | Equivalent ufunc  | Description                         |
|-------------|-------------------|-------------------------------------|
|`+`          |`np.add`           |Addition (e.g., `1 + 1 = 2`)         |
|`-`          |`np.subtract`      |Subtraction (e.g., `3 - 2 = 1`)      |
|`-`          |`np.negative`      |Unary negation (e.g., `-2`)          |
|`*`          |`np.multiply`      |Multiplication (e.g., `2 * 3 = 6`)   |
|`/`          |`np.divide`        |Division (e.g., `3 / 2 = 1.5`)       |
|`//`         |`np.floor_divide`  |Floor division (e.g., `3 // 2 = 1`)  |
|`**`         |`np.power`         |Exponentiation (e.g., `2 ** 3 = 8`)  |
|`%`          |`np.mod`           |Modulus/remainder (e.g., `9 % 4 = 1`)|

Additionally, there are Boolean/bitwise operators

#### Absolute value

In [20]:
x = np.array([-2, -1, 0, 1, 2])
print(np.absolute(x))
print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]
